### ISSUE TITLE
lh-8 does not work (typo in the definitions)

### ISSUE THREAD

**Issue by bora-boris** [chantastic/8-point#1]
Line height for 8*8 does not work, seems like lh-6 is defined twice. I have a PR ready to push but seems like i'm getting denied :/ 

Example change in important.css
<img width="262" alt="screen shot 2018-04-25 at 2 02 21 pm" src="https://user-images.githubusercontent.com/36390301/39272705-7fc49698-4891-11e8-8503-fd505be58115.png">

**Comment by chantastic** [comment]
oh! thanks for pointing this out.

that's weird. you can't pr from your fork?

**Comment by bora-boris** [comment]
just put up a PR, great library by the way!

**Comment by chantastic** [comment]
Fixed by #2 🙌
